export const form = 'form';
export const MIN_LENGTH_ONE = 1;
export enum FormConstants {
  EMAIL_MIN_LENGTH = 10,
  EMAIL_MAX_LENGTH = 130,
  PASSWORD_MIN_LENGTH = 8,
  PASSWORD_MAX_LENGTH = 15,
  MOBILE_MIN_LENGTH = 10,
  MOBILE_MAX_LENGTH = 10,
  FIRST_NAME_MIN_LENGTH = 3,
  FIRST_NAME_MAX_LENGTH = 15,
  OTP_LENGTH = 6,
  TEAM_MIN_LENGTH = 4,
  TEAM_MAX_LENGTH = 25,
  INPUT_MIN_LENGTH = 3,
  INPUT_MAX_LENGTH = 100,
  MIN_AMOUNT_LENGTH = 4,
  MAX_AMOUNT_LENGTH = 5,
}
