export const resources = {
  key: 'Key',
  skills: 'Skills',
  location: 'Location',
  typeOfEmployment: 'Type of Employment',
  sortBy: 'Sort by',
  time: 'Time',
  price: 'Price',
  jobDetails: "Job Details",
  catagory: "Catagory",
  timeLine: "Time line",
  createdAt: "Created at",
  updatedAt: "Updated at",
  description: "Description",
  talkToClient: "Talk to client",
}
