export const resources = {
  key: 'Key',
  skills: 'Skills',
  location: 'Location',
  title: 'Title',
  category: 'Category',
  description: 'Description',
  timeLine: 'Time Line',
  titleIsRequired: 'Title required',
  categoryIsRequired: 'Category required',
  descriptionIsRequired: 'Description required',
  skillIsRequired: 'Skills required',
  timeLineIsRequired: 'Time line required',
  typeOfEmployment: 'Type of Employment',
  sortBy: 'Sort by',
  time: 'Time',
  price: 'Price',
  locationIsRequired: 'Location is required',
  signIn: "Sign In",
  password: "Password",
  email: "Email",
  forgotPassword: "Forgot Password",
  firstNameIsRequired: 'First name is required',
  invalidFirstName: 'Invalid first name',
  lastNameIsRequired: 'Last name is required',
  invalidLastName: 'Invalid last name',
  characters: 'characters',
  firstNameLengthMsg: 'First name must contain',
  lastNameLengthMsg: 'Last name must contain',
  emailIsRequired: 'Email is required',
  invalidEmail: 'Invalid email',
  emaiLengthMsg: 'Email must contain',
  passwordLengthMsg: 'Password must contain',
  invalidPassword: 'Invalid password',
  passwordIsRequired: 'Password is required',
  firstName: 'First Name',
  lastName: 'Last Name',
  client: 'Client',
  freelancer: 'Freelancer',
  signUp: 'Sign Up',
  submit: 'Submit',
  jobDetails: "Job Details",
  catagory: "Catagory",
  createdAt: "Created at",
  updatedAt: "Updated at",
  talkToClient: "Talk to client",
  save: 'Save',
  addJob: 'Add job',
  postJob: 'Post job',
  loading: 'Loading',
  logOut: 'Log Out',
  hireMe: "Hire Me",
  amountEarned: "Amount Earned",
  amountSpent: "Amount Spent",
  amountOnhold: "Amount On-hold",
  memberSince: 'Member Since'
}
